services:
  postgres:
    image: postgres:16
    container_name: ababe-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ababe -d ababe']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: ababe-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    env_file: .env

  ababe-app:
    image: leerura/ababe-app:latest # 여기에 본인 이미지 경로 입력
    container_name: ababe-app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    # ports:
    #   - '80:8080' # Nginx가 프록시하므로 포트 매핑 제거
    command: sh -c "npx prisma db push --config=./prisma.config.ts --schema=./prisma/schema.prisma && node dist/src/main.js"
    # Prisma migration 등을 위해 소스 내의 prisma 폴더와 연동이 필요할 수 있음

  nginx:
    image: nginx:stable-alpine
    container_name: ababe-nginx
    restart: unless-stopped
    depends_on:
      - ababe-app # Nginx가 ababe-app에 의존
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Nginx 프로덕션 설정 파일 (HTTPS + SSE)
      - ./nginx/certs:/etc/nginx/certs:ro # 수동 인증서 경로
      - ./nginx/certbot-etc:/etc/letsencrypt # 인증서 실제 저장소
      - ./nginx/certbot-www:/var/www/certbot:ro # 인증용 챌린지 경로
    command: 'nginx -g "daemon off;"' # Nginx 단순 실행

volumes:
  pgdata:
  redisdata:
