services:
  postgres:
    image: postgres:16
    container_name: ababe-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ababe -d ababe']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: ababe-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    env_file: .env

  ababe-app:
    image: leerura/ababe-app:latest # 여기에 본인 이미지 경로 입력
    container_name: ababe-app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - '80:8080' # EC2 80포트(HTTP)로 접속하면 컨테이너 8080으로 연결
    commands: sh -c "npx prisma db push --config=./prisma.config.ts --schema=./prisma/schema.prisma && node dist/prisma/seed.js && node dist/src/main.js"
    # Prisma migration 등을 위해 소스 내의 prisma 폴더와 연동이 필요할 수 있음

volumes:
  pgdata:
  redisdata:
